# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Elneto CI

on:
  push:
    branches:
      - release
      - 'feature/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Install dependencies
        run: npm ci

      - name: Check out secret
        uses: actions/checkout@v3
        with:
          path: 'src/elneto-secret/'
          repository: teambebop6/elneto-secret
          token: '${{ secrets.ELNETO_SECRET_TOKEN }}'

      - name: Build app
        run: CI=false npm run build

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest"
          message: "Latest release"

      - name: Release app
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist
          token: ${{ secrets.ELNETO_SECRET_TOKEN }}
          repository: teambebop6/elneto-secret
